var car = 'honda';
console.log("is car == 'honda'?i predict true");
console.log(car == 'honda');
console.log("is car != 'toyota'?i predict true");
console.log(car != 'toyota');
console.log("is car === 'honda'?i predict true");
console.log(car === 'honda');
console.log("is car >= 'honda'?i predict true");
console.log(car >= 'honda');
console.log("is car <='honda'?i predict true");
console.log(car <= 'honda');
console.log("is car == 'toyota'?i predict false");
console.log(car == 'toyota');
console.log("is car > 'honda'?i predict false");
console.log(car > 'honda');
console.log("is car > 'mitsubishi'?i predict false");
console.log(car > 'mitsubishi');
console.log("is car <'honda'?i predict false");
console.log(car < 'honda');
console.log("is car >='toyota'?i predict false ");
console.log(car >= 'toyota');
